### ISSUE TITLE
Tests fail when scikit-image colorconv.py module is involved

### ISSUE THREAD

**Issue by ernestoarbitrio** [MPBA/histolab#44]
**Description**
Some assertion errors on test_image_filters happen using `scikit-image==0.17.2` (current version `0.16.2`

**To Reproduce**
1. `pip install scikit-image==0.17.2`
2. `run tests`
3. See errors

**Expected behavior**
No failures at all

**Screenshots**
![image](https://user-images.githubusercontent.com/4196091/84244270-b2b9e400-ab03-11ea-9464-b2eac5b55d10.png)

**Software**
 - OS: MacOSX
 - Python Version: 3.7

IMHO: histolab can't depend on a specific version of a 3rd party app because if that version will be deprecated or no longer updated/supported we will be in troubles. We have to avoid pinning a specific version as dependency (unless it's strictly necessary), in this specific case we need to investigate here https://scikit-image.org/docs/stable/release_notes_and_installation.html and refactor the tests expectations (if needed) according to the changes in this scikit-image version.

**Comment by nicolebussola** [comment]
fix in commit https://github.com/MPBA/histolab/pull/53
